//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Machine.MiFindCustomAndSfcDataServiceService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MiFindCustomAndSfcDataServiceBinding", Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class MiFindCustomAndSfcDataServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback miFindCustomAndSfcDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MiFindCustomAndSfcDataServiceService() {
            this.Url = global::Machine.Properties.Settings.Default.Machine_MiFindCustomAndSfcDataServiceService_MiFindCustomAndSfcDataServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event miFindCustomAndSfcDataCompletedEventHandler miFindCustomAndSfcDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("miFindCustomAndSfcDataResponse", Namespace="http://machineintegration.ws.atlmes.com/")]
        public miFindCustomAndSfcDataResponse miFindCustomAndSfcData([System.Xml.Serialization.XmlElementAttribute("miFindCustomAndSfcData", Namespace="http://machineintegration.ws.atlmes.com/")] miFindCustomAndSfcData miFindCustomAndSfcData1) {
            object[] results = this.Invoke("miFindCustomAndSfcData", new object[] {
                        miFindCustomAndSfcData1});
            return ((miFindCustomAndSfcDataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void miFindCustomAndSfcDataAsync(miFindCustomAndSfcData miFindCustomAndSfcData1) {
            this.miFindCustomAndSfcDataAsync(miFindCustomAndSfcData1, null);
        }
        
        /// <remarks/>
        public void miFindCustomAndSfcDataAsync(miFindCustomAndSfcData miFindCustomAndSfcData1, object userState) {
            if ((this.miFindCustomAndSfcDataOperationCompleted == null)) {
                this.miFindCustomAndSfcDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmiFindCustomAndSfcDataOperationCompleted);
            }
            this.InvokeAsync("miFindCustomAndSfcData", new object[] {
                        miFindCustomAndSfcData1}, this.miFindCustomAndSfcDataOperationCompleted, userState);
        }
        
        private void OnmiFindCustomAndSfcDataOperationCompleted(object arg) {
            if ((this.miFindCustomAndSfcDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.miFindCustomAndSfcDataCompleted(this, new miFindCustomAndSfcDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class miFindCustomAndSfcData {
        
        private findCustomAndSfcDataRequest findCustomAndSfcDataRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public findCustomAndSfcDataRequest FindCustomAndSfcDataRequest {
            get {
                return this.findCustomAndSfcDataRequestField;
            }
            set {
                this.findCustomAndSfcDataRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class findCustomAndSfcDataRequest {
        
        private string siteField;
        
        private string operationField;
        
        private string operationRevisionField;
        
        private string resourceField;
        
        private ObjectAliasEnum[] masterDataArrayField;
        
        private customDataInParametricData[] customDataArrayField;
        
        private string userField;
        
        private string activityField;
        
        private string sfcField;
        
        private string inventoryField;
        
        private bool findSfcByInventoryField;
        
        private modeProcessSFC modeProcessSFCField;
        
        private bool isGetXYField;
        
        private bool isGetCSCField;
        
        private string sfcOrderField;
        
        private string targetOrderField;
        
        private string checkInventoryABField;
        
        private bool showMarkingField;
        
        private bool showMarkingFieldSpecified;
        
        private string findInventoryByGbtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string site {
            get {
                return this.siteField;
            }
            set {
                this.siteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operationRevision {
            get {
                return this.operationRevisionField;
            }
            set {
                this.operationRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("masterDataArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ObjectAliasEnum[] masterDataArray {
            get {
                return this.masterDataArrayField;
            }
            set {
                this.masterDataArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customDataArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public customDataInParametricData[] customDataArray {
            get {
                return this.customDataArrayField;
            }
            set {
                this.customDataArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string activity {
            get {
                return this.activityField;
            }
            set {
                this.activityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sfc {
            get {
                return this.sfcField;
            }
            set {
                this.sfcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inventory {
            get {
                return this.inventoryField;
            }
            set {
                this.inventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool findSfcByInventory {
            get {
                return this.findSfcByInventoryField;
            }
            set {
                this.findSfcByInventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public modeProcessSFC modeProcessSFC {
            get {
                return this.modeProcessSFCField;
            }
            set {
                this.modeProcessSFCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isGetXY {
            get {
                return this.isGetXYField;
            }
            set {
                this.isGetXYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isGetCSC {
            get {
                return this.isGetCSCField;
            }
            set {
                this.isGetCSCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sfcOrder {
            get {
                return this.sfcOrderField;
            }
            set {
                this.sfcOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string targetOrder {
            get {
                return this.targetOrderField;
            }
            set {
                this.targetOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string checkInventoryAB {
            get {
                return this.checkInventoryABField;
            }
            set {
                this.checkInventoryABField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool showMarking {
            get {
                return this.showMarkingField;
            }
            set {
                this.showMarkingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showMarkingSpecified {
            get {
                return this.showMarkingFieldSpecified;
            }
            set {
                this.showMarkingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string findInventoryByGbt {
            get {
                return this.findInventoryByGbtField;
            }
            set {
                this.findInventoryByGbtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sap.com/me/common")]
    public enum ObjectAliasEnum {
        
        /// <remarks/>
        ACTIVITY,
        
        /// <remarks/>
        ACTIVITY_GROUP,
        
        /// <remarks/>
        ACTIVITY_LOG,
        
        /// <remarks/>
        ALARM,
        
        /// <remarks/>
        ALARM_LOG,
        
        /// <remarks/>
        APPLICATION_SETTING,
        
        /// <remarks/>
        ATTACHMENT,
        
        /// <remarks/>
        ATTENDANCE_LOG,
        
        /// <remarks/>
        BACKGROUND_PROCESS,
        
        /// <remarks/>
        BOM,
        
        /// <remarks/>
        BOM_COMPONENT,
        
        /// <remarks/>
        BUYOFF,
        
        /// <remarks/>
        BUYOFF_LOG,
        
        /// <remarks/>
        CERTIFICATION,
        
        /// <remarks/>
        CNC_PROGRAM,
        
        /// <remarks/>
        CONTAINER,
        
        /// <remarks/>
        CONTAINER_DATA,
        
        /// <remarks/>
        COST_CENTER,
        
        /// <remarks/>
        CUSTOMER,
        
        /// <remarks/>
        DATA_FIELD,
        
        /// <remarks/>
        DATA_TYPE,
        
        /// <remarks/>
        DC_GROUP,
        
        /// <remarks/>
        DOCUMENT,
        
        /// <remarks/>
        INVENTORY,
        
        /// <remarks/>
        INVENTORY_LOG,
        
        /// <remarks/>
        ITEM_GROUP,
        
        /// <remarks/>
        LABOR_CHARGE_CODE,
        
        /// <remarks/>
        MESSAGE,
        
        /// <remarks/>
        MESSAGE_LOG,
        
        /// <remarks/>
        MESSAGE_TYPE,
        
        /// <remarks/>
        NC_CODE,
        
        /// <remarks/>
        NEXT_NUMBER,
        
        /// <remarks/>
        OPERATION,
        
        /// <remarks/>
        PROCESS_LOT,
        
        /// <remarks/>
        PRODUCTION_LOG,
        
        /// <remarks/>
        REASON_CODE,
        
        /// <remarks/>
        SAMPLE_PLAN,
        
        /// <remarks/>
        WORK_INSTRUCTION,
        
        /// <remarks/>
        ITEM,
        
        /// <remarks/>
        RESOURCE,
        
        /// <remarks/>
        ROUTER,
        
        /// <remarks/>
        SHOP_ORDER,
        
        /// <remarks/>
        ROUTER_STEP,
        
        /// <remarks/>
        ROUTER_OPERATION,
        
        /// <remarks/>
        SFC,
        
        /// <remarks/>
        USR,
        
        /// <remarks/>
        USER_GROUP,
        
        /// <remarks/>
        WORK_CENTER,
        
        /// <remarks/>
        WORKSTATION,
        
        /// <remarks/>
        RESOURCE_TYPE,
        
        /// <remarks/>
        CUSTOMER_ORDER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class customDataInParametricData {
        
        private ObjectAliasEnum categoryField;
        
        private string dataFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ObjectAliasEnum category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataField {
            get {
                return this.dataFieldField;
            }
            set {
                this.dataFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class customDataOutParametricData {
        
        private ObjectAliasEnum categoryField;
        
        private string dataFieldField;
        
        private string dataAttributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ObjectAliasEnum category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataField {
            get {
                return this.dataFieldField;
            }
            set {
                this.dataFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataAttribute {
            get {
                return this.dataAttributeField;
            }
            set {
                this.dataAttributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class masterData {
        
        private string categoryField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class findCustomAndSfcDataResponse {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private string messageField;
        
        private string sfcField;
        
        private string inventoryField;
        
        private masterData[] masterDataArrayField;
        
        private customDataOutParametricData[] customDataArrayField;
        
        private string xyField;
        
        private string cSCField;
        
        private string systemITEMField;
        
        private string systemSFCField;
        
        private string markingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sfc {
            get {
                return this.sfcField;
            }
            set {
                this.sfcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string inventory {
            get {
                return this.inventoryField;
            }
            set {
                this.inventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("masterDataArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public masterData[] masterDataArray {
            get {
                return this.masterDataArrayField;
            }
            set {
                this.masterDataArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customDataArray", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public customDataOutParametricData[] customDataArray {
            get {
                return this.customDataArrayField;
            }
            set {
                this.customDataArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string xY {
            get {
                return this.xyField;
            }
            set {
                this.xyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CSC {
            get {
                return this.cSCField;
            }
            set {
                this.cSCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string systemITEM {
            get {
                return this.systemITEMField;
            }
            set {
                this.systemITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string systemSFC {
            get {
                return this.systemSFCField;
            }
            set {
                this.systemSFCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string marking {
            get {
                return this.markingField;
            }
            set {
                this.markingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public partial class miFindCustomAndSfcDataResponse {
        
        private findCustomAndSfcDataResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public findCustomAndSfcDataResponse @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://machineintegration.ws.atlmes.com/")]
    public enum modeProcessSFC {
        
        /// <remarks/>
        MODE_NONE,
        
        /// <remarks/>
        MODE_START_SFC,
        
        /// <remarks/>
        MODE_COMPLETE_SFC,
        
        /// <remarks/>
        MODE_PASS_SFC,
        
        /// <remarks/>
        MODE_START_COMPLETE_SFC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void miFindCustomAndSfcDataCompletedEventHandler(object sender, miFindCustomAndSfcDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class miFindCustomAndSfcDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal miFindCustomAndSfcDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public miFindCustomAndSfcDataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((miFindCustomAndSfcDataResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591