//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machine.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ndmesq051.CATLbattery.com:50000/atlmeswebservice/MiCheckProcessLotServiceS" +
            "ervice")]
        public string Machine_WebReference_MiCheckProcessLotServiceService {
            get {
                return ((string)(this["Machine_WebReference_MiCheckProcessLotServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ndmesq051.CATLbattery.com:50000/atlmeswebservice/MiCheckSFCStatusExService" +
            "Service")]
        public string Machine_WebReference1_MiCheckSFCStatusExServiceService {
            get {
                return ((string)(this["Machine_WebReference1_MiCheckSFCStatusExServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ndmesq051.CATLbattery.com:50000/atlmeswebservice/MiBindSFCintoTrayServiceS" +
            "ervice")]
        public string Machine_MiBindSFCintoTrayServiceService_MiBindSFCintoTrayServiceService {
            get {
                return ((string)(this["Machine_MiBindSFCintoTrayServiceService_MiBindSFCintoTrayServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ndmesq051.CATLbattery.com:50000/atlmeswebservice/MachineIntegrationService" +
            "Service")]
        public string Machine_MachineIntegrationServiceService_MachineIntegrationServiceService {
            get {
                return ((string)(this["Machine_MachineIntegrationServiceService_MachineIntegrationServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ndmesq051.CATLbattery.com:50000/atlmeswebservice/CellTestIntegrationServic" +
            "eService")]
        public string Machine_CellTestIntegrationServiceService_CellTestIntegrationServiceService {
            get {
                return ((string)(this["Machine_CellTestIntegrationServiceService_CellTestIntegrationServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ndmesq051.CATLbattery.com:50000/atlmeswebservice/MiChangeResourceAndProces" +
            "sLotServiceService")]
        public string Machine_MiChangeResourceAndProcessLotServiceService_MiChangeResourceAndProcessLotServiceService {
            get {
                return ((string)(this["Machine_MiChangeResourceAndProcessLotServiceService_MiChangeResourceAndProcessLot" +
                    "ServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ndmesq051.CATLbattery.com:50000/atlmeswebservice/MiCloseNcAndProcessServic" +
            "eService")]
        public string Machine_MiCloseNcAndProcessService_MiCloseNcAndProcessServiceService {
            get {
                return ((string)(this["Machine_MiCloseNcAndProcessService_MiCloseNcAndProcessServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://xpmesp021.catlfaw.com:50100/atlmeswebservice/DataCollectForResourceFAIServ" +
            "iceService")]
        public string Machine_DataCollectForResourceFAIService_DataCollectForResourceFAIServiceService {
            get {
                return ((string)(this["Machine_DataCollectForResourceFAIService_DataCollectForResourceFAIServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gacmes1p024.catlgac.cn:50400/atlmeswebservice/MiMESIntegrationForParameter" +
            "ValueIssueServiceService")]
        public string Machine_MiMESIntegrationForParameterValueIssueServiceService_MiMESIntegrationForParameterValueIssueServiceService {
            get {
                return ((string)(this["Machine_MiMESIntegrationForParameterValueIssueServiceService_MiMESIntegrationForP" +
                    "arameterValueIssueServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gacmes1p022.catlgac.cn:50200/atlmeswebservice/MiFindCustomAndSfcDataServic" +
            "eService")]
        public string Machine_MiFindCustomAndSfcDataServiceService_MiFindCustomAndSfcDataServiceService {
            get {
                return ((string)(this["Machine_MiFindCustomAndSfcDataServiceService_MiFindCustomAndSfcDataServiceService" +
                    ""]));
            }
        }
    }
}
